language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests. Yes there will be tests"

script:
  - docker --version # print the version for logging here.
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  #Tagging
  - docker tag reverseproxy steemz/udagram-reverseproxy-two:v4a
  - docker tag udagram-api-feed steemz/udagram-api-feed-two:v4a
  - docker tag udagram-api-user steemz/udagram-api-user-two:v4a
  - docker tag udagram-frontend steemz/udagram-frontend-two:local3

# Tasks to perform after the process is successful. Formatting the Docker username and password
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push steemz/udagram-reverseproxy-two:v4a
  - docker push steemz/udagram-api-feed-two:v4a
  - docker push steemz/udagram-api-user-two:v4a
  - docker push steemz/udagram-frontend-two:local3